### ISSUE TITLE
Problems Accessing Data

### ISSUE THREAD

**Issue by talswisa** [MadryLab/datamodels-data#1]
Hey,
Thank you for this very interesting work!
I am having trouble accessing the data - after running:
aws s3api get-object --bucket madrylab-datamodels \
                     --key cifar/data/test_margins_50pct.npy \
                     --request-payer requester \
                     test_margins_50pct.npy
I get:
An error occurred (AccessDenied) when calling the GetObject operation: Access Denied

Any ideas how to fix this?

**Comment by sung-max** [comment]
Hi!

Thank you for your comment on our work!

I am not sure why you are seeing this error.
Did you run/setup `aws configure` before running above?

**Comment by talswisa** [comment]
Thank you for your answer.
It turns out I had permissions issues. I fixed them and everything works now :)

**Comment by sung-max** [comment]
Great! Glad it's working. Thanks for checking out our data!

**Comment by hlzhang109** [comment]
How long does it take to download it? Do you know how to solve the issue running the command gives no reaction?

**Comment by Kranito** [comment]
> 
would u mind telling me how to fix it? I met a same question
