### ISSUE TITLE
Can only download data for 50 pct

### ISSUE THREAD

**Issue by talswisa** [MadryLab/datamodels-data#2]
Hey :)
For some reason I can only download the datamodel weights for 50 pct with the command:  aws s3 cp --request-payer requester s3://madrylab-datamodels/cifar/datamodels/train_50pct.pt .

When changing 50 to 10/20/75 I get the error: fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden

Do you have any idea why this happens?

**Comment by andrewilyas** [comment]
Hi! Currently the only training-set datamodels available are for alpha = 50%. For now, you should be able to download test-set datamodels for other values of alpha (e.g., test_20pct.pt) or the 50% datamodels that you linked above.

**Comment by jerryjonghopark** [comment]
Hello! Are there any plans to release the training-set datamodels for other alpha values as well? Thank you.
